import { ICP } from './types';

export const initialICPs: ICP[] = [
  {
    id: "1",
    name: "Mark McFatridge",
    title: "Founder & CEO | Host",
    company: "Quade | Igniting the CEO Within Podcast",
    linkedinUrl: "https://www.linkedin.com/in/mark-mcfatridge",
    trojanHorseSent: true,
    dateSent: "2026-04-28",
    response: "No Reply",
    topic: "",
    transcript: "When you screw up, own that stuff. Hey, I messed up... honesty is a part of character...",
    point: "how hiding your mistakes destroys trust.",
    timestamps: "edited already",
    link: "https://tinyurl.com/4aujnvms",
    status: "done"
  },
  {
    id: "1b",
    name: "Ged Roberts",
    title: "CEO | Host",
    company: "Crystalyzer | Metronomics Podcast",
    linkedinUrl: "https://www.linkedin.com/in/gedroberts",
    trojanHorseSent: true,
    dateSent: "2026-04-28",
    response: "Positive",
    topic: "",
    transcript: "",
    point: "",
    timestamps: "",
    link: "https://www.youtube.com/watch?v=o5sf9lVTR74&list=PL2gnjmpLjfGj1RBXYDZHgpwGrRC7N4Tvr",
    status: "done"
  },
  {
    id: "2",
    name: "Chris Anderson",
    title: "Founder & CEO | Host",
    company: "Elevate Media | Elevate Media Podcast",
    linkedinUrl: "https://www.linkedin.com/in/chris1anderson",
    trojanHorseSent: true,
    dateSent: "2026-04-28",
    response: "No Reply",
    topic: "",
    transcript: "Let's say you had a side business... That is mediocrity. I'm just calling a thing a thing.",
    point: "in marriage, More effort does not equal more value",
    timestamps: "18:12 - 18:52",
    link: "https://tinyurl.com/yb5wj8ah",
    status: "done"
  },
  {
    id: "2b",
    name: "Richard Atherton",
    title: "Partner | Host",
    company: "FirstHuman | Being Human Podcast",
    linkedinUrl: "https://www.linkedin.com/in/richardatherton-firsthuman",
    trojanHorseSent: true,
    dateSent: "2026-04-28",
    response: "Positive",
    topic: "",
    transcript: "",
    point: "",
    timestamps: "",
    link: "https://www.youtube.com/watch?v=DQ37QRJVf-s&list=PLjqL7UmSeAjbHF3bR4JTrGGrWbVFLLldF",
    status: "done"
  },
  {
    id: "3",
    name: "Sten Morgan",
    title: "Host Becoming an Elite Financial Advisor Podcast | Founder of Elite Advisor Network",
    company: "Elite Advisor Network",
    linkedinUrl: "https://www.linkedin.com/in/sten-morgan/",
    trojanHorseSent: true,
    dateSent: "2026-04-28",
    response: "No Reply",
    topic: "Human Element in Wealth Management",
    transcript: "5 years ago, we were talking to um a prospective client and this client was very wealthy, you know, probably over 100 million of net worth... and that's that's what people need now you need a lot of good technical technical stuff kind of, you know, behind you. You need the skills. You need to be able to do a good job. But we could talk a lot about that, but at the end of the day, it's a human, right? And they have questions.",
    point: "Even the richest people are asking the same basic fear-based questions",
    timestamps: "-8:15 -9:02 -",
    link: "https://tinyurl.com/3ezecf5d",
    status: "done"
  },
  {
    id: "4",
    name: "Matthew Jarvis",
    title: "co-host of The Perfect RIA podcast & co-founder of The Perfect RIA",
    company: "The Perfect RIA",
    linkedinUrl: "https://www.linkedin.com/in/mpjarvis/",
    trojanHorseSent: false,
    dateSent: null,
    response: "No Reply",
    topic: "",
    transcript: "we think this that our value is in how much we talk... they would almost pay you double if you talked half as much.",
    point: "Clients pay for clarity, not more words.",
    timestamps: "08:26 - 09:09",
    link: "https://tinyurl.com/3ux9b6hk",
    status: "draft"
  },
  {
    id: "5",
    name: "Micah Shilanski",
    title: "co-host of The Perfect RIA podcast & co-founder of The Perfect RIA",
    company: "The Perfect RIA",
    linkedinUrl: "https://www.linkedin.com/in/micahshilanski/",
    trojanHorseSent: false,
    dateSent: null,
    response: "No Reply",
    topic: "",
    transcript: "This will really hit at your core... You are being judged all the time on did you do what you said you were going to do.",
    point: "If you don't respect time, you're breaking trust.",
    timestamps: "01:43 - 02:06",
    link: "https://tinyurl.com/mrnrfjkm",
    status: "draft"
  },
  {
    id: "6",
    name: "Tyson Mutrux",
    title: "Helping the Injured Get Medical Care, Bills Paid, and 💵 in their Pockets",
    company: "Host of Maximum Lawyer Podcast | Managing Partner at Mutrux firm injury lawyers",
    linkedinUrl: "https://www.linkedin.com/in/tysonmutrux/",
    trojanHorseSent: true,
    dateSent: "2026-04-28",
    response: "No Reply",
    topic: "",
    transcript: "Our missed call rate went from 23% to 1%... So, if you're not doing it right now, you are leaving money on the table.",
    point: "Fixing missed calls and follow-ups can literally 3x your clients without getting more leads.",
    timestamps: "16:00 - 17:17",
    link: "https://tinyurl.com/yc27jbsy",
    status: "done"
  },
  {
    id: "7",
    name: "Misty Lynch, CFP®",
    title: "CEO at Sound View Financial Advisors LLC",
    company: "CEO at sound Advisors | Host of Demystifying Money Podcast",
    linkedinUrl: "https://www.linkedin.com/in/mistylynch/",
    trojanHorseSent: true,
    dateSent: "2026-04-28",
    response: "No Reply",
    topic: "",
    transcript: "Either you pay full price or I give it for free. Yeah. Those are my two categories. There's no discounts ever. So, it's not that someone is getting a discount and you're not. No one gets a discount.",
    point: "Either full price or free — no discounts ever.",
    timestamps: "38:07 - 30:22",
    link: "https://tinyurl.com/4rc6yb3w",
    status: "done"
  },
  {
    id: "8",
    name: "Stephanie A. Everett",
    title: "Co-Host, The Lawyerist Podcast",
    company: "Co-Host, The Lawyerist Podcast | CGO at Affinity Consulting Group",
    linkedinUrl: "https://www.linkedin.com/in/stephanieaeverett/",
    trojanHorseSent: true,
    dateSent: "2026-04-28",
    response: "No Reply",
    topic: "",
    transcript: "The number used to be anywhere between like 5 to 10 interactions before you got to a a win... And so I think people give up because they're not persistent or they're not disciplined or they forget.",
    point: "Most wins now take 10–18 interactions, so people quit way too early.",
    timestamps: "15:04 - 15:56",
    link: "https://tinyurl.com/bbcbpnb6",
    status: "done"
  },
  {
    id: "9",
    name: "Kevin Daisey",
    title: "Helping Lawyers Grow Their Firms - Host of The Managing Partners Podcast and Mastermind",
    company: "Host of The Managing Partners Podcast | Founder Array Digital",
    linkedinUrl: "https://www.linkedin.com/in/kevindaisey/",
    trojanHorseSent: true,
    dateSent: "2026-04-28",
    response: "No Reply",
    topic: "",
    transcript: "But there are things and you'd be surprised at how many PI firms are sloppy with respect to prepaid case cost... It's just like losing a case, all those all those case costs are just gone.",
    point: "If you don't track case costs properly, you're literally losing money you already won.",
    timestamps: "27:10 - 28:12",
    link: "https://tinyurl.com/5dzffcsu",
    status: "done"
  },
  {
    id: "10",
    name: "Bo Hanson",
    title: "Partner, Abound Wealth Management | Co-Host of The Money-Guy Show",
    company: "Partner at Abound Wealth | Host of The Money Guy Show",
    linkedinUrl: "https://www.linkedin.com/in/boh01",
    trojanHorseSent: true,
    dateSent: "2026-04-28",
    response: "No Reply",
    topic: "",
    transcript: "Cars are the biggest wealth killer... There's a lot of people out there that are driving around cars that cost more than they make in a year.",
    point: "People are driving cars that cost more than they make in a year.",
    timestamps: "1:02 - 1:54",
    link: "https://tinyurl.com/3a8bs7au",
    status: "done"
  },
  {
    id: "10b",
    name: "Brian Preston",
    title: "Founder and Host of The Money Guy Show / Principal, Abound Wealth",
    company: "Managing Partner at Abound Wealth | Host of The Money Guy Show",
    linkedinUrl: "https://www.linkedin.com/in/moneyguy/",
    trojanHorseSent: true,
    dateSent: "2026-04-28",
    response: "No Reply",
    topic: "",
    transcript: "The health savings account is pretty magical because it offers triple tax advantage... So there are four distinct tax advantages to the HSA.",
    point: "An HSA actually stacks up to four tax advantages",
    timestamps: "6:51 - 7:55",
    link: "https://tinyurl.com/82zv7w7r",
    status: "done"
  },
  {
    id: "11",
    name: "Stephen E. Seckler",
    title: "Attorney Career & Marketing Coach | Helping Lawyers Act Like Entrepreneurs",
    company: "Host of Counsel to Counsel Podcast | President Seckler Attorney Coaching",
    linkedinUrl: "https://www.linkedin.com/in/stephenseckler/",
    trojanHorseSent: false,
    dateSent: null,
    response: "No Reply",
    topic: "",
    transcript: "We don't set boundaries and we don't delegate well because we want to make sure everything is just perfect... Most said things fall apart or things are in chaos. And that's not sustainable.",
    point: "Perfectionism kills delegation.",
    timestamps: "19:17 - 20:39",
    link: "https://www.youtube.com/watch?v=p72LaSqpLuw",
    status: "draft"
  },
  {
    id: "12",
    name: "Michael Kitces",
    title: "Chief Financial Planning Nerd",
    company: "Host of Financial Advisor Success Podcast | Chief Financial Planning Nerd at Kitces.com",
    linkedinUrl: "https://www.linkedin.com/in/michaelkitces/",
    trojanHorseSent: false,
    dateSent: null,
    response: "No Reply",
    topic: "",
    transcript: "I wouldn't want to work at a firm that took this risk to zero... someone else is going to have a checklist to make sure I'm doing my checklist...",
    point: "Trying to eliminate all risk just buries you in bureaucracy.",
    timestamps: "placeholders",
    link: "https://tinyurl.com/4377m8hv",
    status: "draft"
  },
  {
    id: "13",
    name: "Carl Richards",
    title: "Clear thinking about the decisions that shape your life",
    company: "Co-Host of Kitces & Carl – Real Talk for FAs Podcast | Founder The Behavior Gap",
    linkedinUrl: "https://www.linkedin.com/in/thinkingcarl/",
    trojanHorseSent: false,
    dateSent: null,
    response: "No Reply",
    topic: "",
    transcript: "The doctors who get sued the most are not the doctors that make the most mistakes. They're the doctors that have the worst bedside manner... They're there because you had the worst relationship.",
    point: "Bad relationships get you sued more than bad work.",
    timestamps: "placeholders",
    link: "https://tinyurl.com/3eec9ykz",
    status: "draft"
  },
  {
    id: "14",
    name: "Eric Roberge (CFP®)",
    title: "Creating optimized financial plans for successful professionals",
    company: "Host of Money for Life (CFP®) Podcast | Founder Beyond Your Hammock",
    linkedinUrl: "https://www.linkedin.com/in/ericroberge/",
    trojanHorseSent: false,
    dateSent: null,
    response: "No Reply",
    topic: "",
    transcript: "this is where it's kind of like running a business, right?... If you're making less net, even if your salary is more, there's a problem there maybe, right?",
    point: "Only your real take-home pay matters.",
    timestamps: "placeholders",
    link: "https://tinyurl.com/3bauhfhx",
    status: "draft"
  },
  {
    id: "15",
    name: "Tim Meisenheimer, CFA, CFP®",
    title: "Owner & CEO | Leveraging Portfolios to Change the World",
    company: "Host of Beyond Wealth Riches | CEO Streamline Financial Services",
    linkedinUrl: "https://www.linkedin.com/in/meisy/",
    trojanHorseSent: false,
    dateSent: null,
    response: "No Reply",
    topic: "",
    transcript: "what you spend money on shows what you value... what we do with our res isn't neutral for us. It's actually shaping us in one way or another.",
    point: "Your spending shapes who you become.",
    timestamps: "48:35 - 49:50",
    link: "https://tinyurl.com/ye28z4my",
    status: "draft"
  },
  {
    id: "16",
    name: "Todd Weyandt",
    title: "B2B SaaS Growth Architect | Category-Defining GTM Systems",
    company: "Host of Bridging the Gap Podcast | Head of Marketing GRAITEC GROUP",
    linkedinUrl: "https://www.linkedin.com/in/toddweyandt/",
    trojanHorseSent: false,
    dateSent: null,
    response: "No Reply",
    topic: "",
    transcript: "There's a fire at your home... The military has taught us that the generals stand in the back because the emotions need to be calmed to create a smarter delivery.",
    point: "In a crisis, calm leadership beats chaos.",
    timestamps: "16:38 - 17:35",
    link: "https://tinyurl.com/2s3rbx93",
    status: "draft"
  },
  {
    id: "17",
    name: "Matt Reiner (CFA, CFP®)",
    title: "The Future of Wealth Management Is More Human, Not Less",
    company: "Host of FutureProof Advisor Podcast | Managing Partner CIA",
    linkedinUrl: "https://www.linkedin.com/in/matt-reiner-cfa-cfp%C2%AE-35159216/",
    trojanHorseSent: false,
    dateSent: null,
    response: "No Reply",
    topic: "AI For RIAs: The Trends That Will Impact Your firm",
    transcript: "Think about this. If you can have AI help you analyze thousands of people's of health records very quickly... AI + human oversight lets you serve more people better.",
    point: "AI + human oversight lets you serve more people better.",
    timestamps: "13:43 - 14:38",
    link: "https://www.youtube.com/watch?v=eoCanJ-8lDE",
    status: "draft"
  },
  {
    id: "18",
    name: "Richard Gearhart",
    title: "Founder of Gearhart Law and Host of Passage to Profit Radio Show",
    company: "Gearhart Law",
    linkedinUrl: "https://www.linkedin.com/in/richardgearhart",
    trojanHorseSent: false,
    dateSent: null,
    response: "No Reply",
    topic: "The Startup Myth Most Founders Get Wrong!",
    transcript: "Entrepreneurship is a tough game. It can be tough game or we could see it as play...",
    point: "Treat entrepreneurship like a game, not a grind.",
    timestamps: "18:42 - 19:36",
    link: "https://tinyurl.com/3eec9ykz",
    status: "draft"
  },
  {
    id: "19",
    name: "Christie McEvoy-Derrico",
    title: "Attorney | Author of HER HONOR | Co-Host of The Balance Dilemma Podcast",
    company: "VILLAGE OF MAMARONECK",
    linkedinUrl: "https://www.linkedin.com/in/christie-mcevoy-derrico",
    trojanHorseSent: false,
    dateSent: null,
    response: "No Reply",
    topic: "",
    transcript: "",
    point: "",
    timestamps: "",
    link: "https://www.youtube.com/watch?v=co4kvK3pS7E",
    status: "draft"
  },
  {
    id: "20",
    name: "Brian Beckcom",
    title: "Board Certified Texas Trial Lawyer | Serious Personal Injury Cases",
    company: "VB Attorneys",
    linkedinUrl: "https://www.linkedin.com/in/brianbeckcom",
    trojanHorseSent: false,
    dateSent: null,
    response: "No Reply",
    topic: "",
    transcript: "",
    point: "",
    timestamps: "",
    link: "https://www.youtube.com/watch?v=vGfNX3G1TOg",
    status: "draft"
  },
  {
    id: "21",
    name: "Michele Locke",
    title: "lovelustlaw Podcast Host I Family Law Attorney I Look good, feel good, do good!",
    company: "COLDWELL BOWES, LLP",
    linkedinUrl: "https://www.linkedin.com/in/michele-locke",
    trojanHorseSent: false,
    dateSent: null,
    response: "No Reply",
    topic: "",
    transcript: "",
    point: "",
    timestamps: "",
    link: "https://www.youtube.com/watch?v=k57p0BqXGj4",
    status: "draft"
  },
  {
    id: "22",
    name: "Jaime Santana",
    title: "Owner of Santana Law Firm, Actor-SAG, Host of The Santana Effect",
    company: "Santana Law Firm",
    linkedinUrl: "https://www.linkedin.com/in/jaime-santana-esq-48511111",
    trojanHorseSent: false,
    dateSent: null,
    response: "No Reply",
    topic: "",
    transcript: "",
    point: "",
    timestamps: "",
    link: "https://www.youtube.com/watch?v=lkqpeWCLvA8",
    status: "draft"
  }
];
